version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultron-website
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
